package com.repolens.ai.summary;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.repolens.ai.AiProvider;
import com.repolens.ai.AiProviderStatus;
import com.repolens.ai.AiProviderType;
import com.repolens.ai.AiService;
import com.repolens.analysis.architecture.ArchitectureAnalysis;
import com.repolens.analysis.architecture.ArchitectureType;
import com.repolens.analysis.detector.BuildTool;
import com.repolens.analysis.detector.ProgrammingLanguage;
import com.repolens.analysis.health.HealthFinding;
import com.repolens.analysis.health.HealthGrade;
import com.repolens.analysis.health.RepositoryHealthAnalysis;
import com.repolens.analysis.snapshot.RepositorySnapshotAnalysis;
import com.repolens.analysis.snapshot.RepositoryStructure;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;

class DefaultAiSummaryServiceTest {

    @Test
    void shouldConvertAiJsonIntoRepositorySummary() {

        AiProvider provider = new AiProvider() {

            @Override
            public AiProviderType type() {
                return AiProviderType.GEMINI;
            }

            @Override
            public AiProviderStatus status() {
                return AiProviderStatus.AVAILABLE;
            }

            @Override
            public boolean isAvailable() {
                return true;
            }

            @Override
            public String generate(String prompt) {
                return """
                        {
                          "summary": "Java Maven repository with layered architecture.",
                          "strengths": [
                            "Uses a recognised build system",
                            "Has documented architecture"
                          ],
                          "concerns": [
                            "Testing coverage is unclear"
                          ],
                          "recommendations": [
                            "Add more automated tests"
                          ]
                        }
                        """;
            }
        };

        AiService aiService = new AiService() {

            @Override
            public List<AiProviderType> getAvailableProviders() {
                return List.of(AiProviderType.GEMINI);
            }

            @Override
            public boolean isAiAvailable() {
                return true;
            }

            @Override
            public AiProvider getProvider(AiProviderType type) {
                return provider;
            }
        };

        RepositorySnapshotAnalysis analysis = createAnalysis();

        DefaultAiSummaryService service =
                new DefaultAiSummaryService(
                        aiService,
                        List.of(provider),
                        new ObjectMapper()
                );

        AiRepositorySummary result =
                service.generateSummary(analysis);

        assertEquals(
                "Java Maven repository with layered architecture.",
                result.summary()
        );

        assertEquals(2, result.strengths().size());
        assertEquals(1, result.concerns().size());
        assertEquals(1, result.recommendations().size());
    }

    @Test
    void shouldUseExplicitProvider() {

        AiProvider provider = new AiProvider() {

            @Override
            public AiProviderType type() {
                return AiProviderType.GEMINI;
            }

            @Override
            public AiProviderStatus status() {
                return AiProviderStatus.AVAILABLE;
            }

            @Override
            public boolean isAvailable() {
                return true;
            }

            @Override
            public String generate(String prompt) {
                return """
                        {
                          "summary": "Generated by Gemini.",
                          "strengths": [],
                          "concerns": [],
                          "recommendations": []
                        }
                        """;
            }
        };

        AiService aiService = new AiService() {

            @Override
            public List<AiProviderType> getAvailableProviders() {
                return List.of(AiProviderType.GEMINI);
            }

            @Override
            public boolean isAiAvailable() {
                return true;
            }

            @Override
            public AiProvider getProvider(AiProviderType type) {
                return provider;
            }
        };

        DefaultAiSummaryService service =
                new DefaultAiSummaryService(
                        aiService,
                        List.of(provider),
                        new ObjectMapper()
                );

        AiRepositorySummary result =
                service.generateSummary(
                        createAnalysis(),
                        AiProviderType.GEMINI
                );

        assertEquals(
                "Generated by Gemini.",
                result.summary()
        );
    }

    private RepositorySnapshotAnalysis createAnalysis() {
        return new RepositorySnapshotAnalysis(
                true,
                true,
                true,
                true,
                Set.of(BuildTool.MAVEN),
                Set.of(ProgrammingLanguage.JAVA),
                new RepositoryStructure(
                        20,
                        5,
                        10,
                        2,
                        4
                ),
                new ArchitectureAnalysis(
                        ArchitectureType.LAYERED,
                        List.of(ArchitectureType.LAYERED),
                        List.of()
                ),
                new RepositoryHealthAnalysis(
                        85,
                        HealthGrade.EXCELLENT,
                        List.of(
                                new HealthFinding(
                                        "Documentation",
                                        20,
                                        "README present"
                                )
                        )
                )
        );
    }
}