spring.application.name=repolens

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/repolens}
spring.datasource.username=${DB_USERNAME:repolens}
spring.datasource.password=${DB_PASSWORD:repolens}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

github.api.base-url=https://api.github.com
github.api.token=${GITHUB_TOKEN:}

repolens.ai.gemini.enabled=${GEMINI_ENABLED:false}
repolens.ai.gemini.api-key=${GEMINI_API_KEY:}
repolens.ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
repolens.ai.gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
