spring.application.name=repolens

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/repolens}
spring.datasource.username=${DB_USERNAME:repolens}
spring.datasource.password=${DB_PASSWORD:repolens}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

github.api.base-url=https://api.github.com
github.api.token=${GITHUB_TOKEN:}

